// ソースコードへようこそ！ // 答えを求めて来たのですか？ //
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const STORAGE_KEY='zmtq_progress_v1';
const APP_VERSION='2026.09.11-prototype.4';
let stages=[];
let state={stage:null,mode:null,index:0,data:null,solved:false};
const progress=()=>JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"clears":{},"achievements":{}}');
const save=p=>localStorage.setItem(STORAGE_KEY,JSON.stringify(p));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fetchJSON=async(url,options={})=>{const r=await fetch(url,options);if(!r.ok)throw new Error(url);return r.json()};
function normalize(s){return s.normalize('NFKC').trim().replace(/[\s　]+/g,'').toLowerCase()}
async function sha256(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(normalize(s)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function setAccent(color='#b99a67'){document.documentElement.style.setProperty('--stage-accent',color)}
function statusFor(id,mode){const p=progress();if(p.clears[`${id}:${mode}`])return'CLEAR済み';if(mode==='hard'&&!p.clears[`${id}:normal`])return'LOCKED';return'プレイ可能'}
function home(updateHistory=true){if(updateHistory)history.pushState({},'',location.pathname);state={stage:null,mode:null,index:0,data:null,solved:false};setAccent();$('#app').innerHTML=`<section class="hero"><p class="lead">各地に残された十の謎。勇者たちが新たな地を訪れるたび、ステージが解放されていきます。</p></section><h1 class="section-title">STAGES</h1><section class="stage-grid">${stages.map((s,i)=>`<article class="stage-card" style="--accent:${s.accent}"><span class="stage-index">0${i+1}</span><h2>${esc(s.name)}</h2><div class="modes">${['normal','hard'].map(m=>{const st=statusFor(s.id,m);return`<button class="mode-button" data-stage="${s.id}" data-mode="${m}" ${st==='LOCKED'?'disabled':''}>${m.toUpperCase()}<small>${st}</small></button>`}).join('')}</div></article>`).join('')}</section>`;$$('.mode-button').forEach(b=>b.onclick=()=>start(b.dataset.stage,b.dataset.mode,true))}
function playTransition(onCovered){return new Promise(resolve=>{const t=$('#stageTransition');t.classList.remove('active','leaving');void t.offsetWidth;t.classList.add('active');setTimeout(()=>{if(onCovered)onCovered();t.classList.add('leaving')},1050);setTimeout(()=>{t.classList.remove('active','leaving');resolve()},2200)})}
async function goHomeWithTransition(){await playTransition(()=>home());}
async function start(id,mode,animate=false){const s=stages.find(x=>x.id===id);if(!s)return home();if(mode==='hard'&&statusFor(id,mode)==='LOCKED')return home();state.stage=s;state.mode=mode;state.index=0;state.solved=false;setAccent(s.accent);try{state.data=await fetchJSON(s[`${mode}Data`],{cache:'no-store'});const show=()=>{history.pushState({},'',`?stage=${encodeURIComponent(id)}&mode=${mode}`);renderQuestion()};if(animate)await playTransition(show);else show()}catch{showError('問題データを読み込めませんでした。ローカルではWebサーバーから開いてください。')}}
function questionMarkup(q){
  if(q.type==='image'&&q.image){
    const alt=q.alt||'謎解き問題の画像';
    const caption=q.question?`<p class="image-question-text">${esc(q.question)}</p>`:'';
    return `<figure class="puzzle-image-wrap"><img class="puzzle-image" src="${esc(q.image)}" alt="${esc(alt)}" loading="eager" decoding="async">${caption}</figure>`;
  }
  return `<p class="text-question">${esc(q.question||'')}</p>`;
}
function renderQuestion(){const q=state.data.questions[state.index],n=state.data.questions.length;state.solved=false;$('#app').innerHTML=`<section class="puzzle-shell"><div class="puzzle-meta"><span>${esc(state.stage.name)} · ${state.mode.toUpperCase()}</span><span>${state.index+1} / ${n}</span></div><div class="progress"><span style="width:${(state.index+1)/n*100}%"></span></div><div class="eyebrow">QUESTION ${String(state.index+1).padStart(2,'0')}</div><div class="question">${questionMarkup(q)}</div><p class="guide">${esc(state.data.inputGuide)}</p><form class="answer-area"><input id="answer" aria-label="答え" autocomplete="off" required><button class="primary" type="submit">回答する</button></form><p id="feedback" class="feedback" aria-live="polite"></p><div class="actions"><button class="secondary hint" data-hint="1">ヒント1</button><button class="secondary hint" data-hint="2">ヒント2</button><button id="next" class="primary" hidden>次へ</button></div><div id="hintBox"></div></section>`;$('.answer-area').onsubmit=checkAnswer;$$('.hint').forEach(b=>b.onclick=()=>showHint(+b.dataset.hint));$('#next').onclick=next;$('#answer').focus()}
async function checkAnswer(e){e.preventDefault();if(state.solved)return;const q=state.data.questions[state.index],digest=await sha256($('#answer').value),fb=$('#feedback');if(digest===q.answerHash){state.solved=true;fb.className='feedback ok';fb.textContent='正解です。「次へ」を押すと先へ進めます。';$('#next').hidden=false;$('#answer').disabled=true}else{fb.className='feedback bad';fb.textContent='違うようです。もう一度お試しください。';$('#answer').select()}}
function showHint(n){const q=state.data.questions[state.index];$('#hintBox').innerHTML=`<div class="hint-box"><span class="eyebrow">HINT ${n}</span><br>${esc(q[`hint${n}`])}</div>`}
function next(){if(!state.solved)return;if(state.index<state.data.questions.length-1){state.index++;renderQuestion()}else playTransition(complete)}
function complete(){const p=progress(),key=`${state.stage.id}:${state.mode}`;const firstClear=p.clears[key]||new Date().toISOString();p.clears[key]=firstClear;if(!p.achievements[key])p.achievements[key]={unlockedAt:firstClear,title:`${state.stage.name}（${state.mode.toUpperCase()}）をクリア`};save(p);const shareUrl=`${location.origin}${location.pathname}?stage=${state.stage.id}&mode=${state.mode}`,text=encodeURIComponent(`ZMTQ謎解き、${state.stage.name}（${state.mode.toUpperCase()}）をクリアしました。\n${shareUrl}\n\n#ZMTQ_RAtR`);$('#app').innerHTML=`<section class="clear"><div class="clear-symbol">◇</div><div class="eyebrow">EXHIBITION COMPLETED</div><h1>CLEAR</h1><p>${esc(state.stage.name)}での謎解きを終えました。</p>${state.mode==='normal'?'<p class="feedback ok">HARDが解放されました。</p>':''}<div class="clear-actions"><button id="toHome" class="primary">ステージ選択へ戻る</button><a class="secondary" target="_blank" rel="noopener" href="https://twitter.com/intent/tweet?text=${text}">Xで共有する</a></div></section>`;$('#toHome').onclick=goHomeWithTransition}
function showError(msg){$('#app').innerHTML=`<section class="clear"><h1>読み込みエラー</h1><p>${esc(msg)}</p><button class="primary" onclick="location.reload()">再読み込み</button></section>`}
async function modal(type){const c=$('#modalContent');if(type==='howto')c.innerHTML='<h2>遊び方</h2><p>地名ごとのステージには10問あります。ひらがなで答えを入力し、正解すると次へ進めます。NORMALをクリアすると同地域のHARDが解放されます。各問題には2つのヒントがありますが、答えそのものは表示されません。</p>';if(type==='updates'){const u=await fetchJSON(`data/updates.json?t=${Date.now()}`,{cache:'no-store'});c.innerHTML=`<h2>更新情報</h2><ul class="update-list">${u.map(x=>`<li><time>${esc(x.date)}</time>${esc(x.text)}</li>`).join('')}</ul>`}if(type==='achievements'){const a=Object.values(progress().achievements);c.innerHTML=`<h2>実績</h2>${a.length?`<ul class="achievement-list">${a.map(x=>`<li>◇ ${esc(x.title)}<br><small>${new Date(x.unlockedAt).toLocaleDateString('ja-JP')}</small></li>`).join('')}</ul>`:'<p>まだ解除された実績はありません。</p>'}`}$('#modal').showModal()}
async function checkVersion(){try{const v=await fetchJSON(`data/version.json?t=${Date.now()}`,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(v.version!==APP_VERSION){$('#updateNotice').hidden=false;return false}return true}catch{return null}}
async function init(){try{stages=await fetchJSON('data/stages.json');$$('[data-modal]').forEach(b=>b.onclick=()=>modal(b.dataset.modal));$('.modal-close').onclick=()=>$('#modal').close();$('#reloadButton').onclick=()=>{const u=new URL(location.href);u.searchParams.set('_refresh',Date.now());location.replace(u)};window.onpopstate=home;const p=new URLSearchParams(location.search),id=p.get('stage'),mode=p.get('mode');if(id&&['normal','hard'].includes(mode))await start(id,mode);else home();checkVersion();setTimeout(checkVersion,2500);setInterval(checkVersion,60000)}catch{showError('初期データを読み込めませんでした。READMEの手順で起動してください。')}}
init();
