// ソースコードへようこそ！ // 答えを求めて来たのですか？ //
const $ = (s, p=document) => p.querySelector(s);
const STORAGE_KEY = 'zmtq_progress_v1';
let stages=[];
let state={stage:null,mode:null,index:0,data:null,solved:false};
const progress=()=>JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"clears":{},"achievements":{}}');
const save=p=>localStorage.setItem(STORAGE_KEY,JSON.stringify(p));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fetchJSON=async url=>{const r=await fetch(url);if(!r.ok)throw new Error(url);return r.json()};
function normalize(s){return s.normalize('NFKC').trim().replace(/[\s　]+/g,'').toLowerCase()}
async function sha256(s){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(normalize(s)));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function statusFor(id,mode){const p=progress();if(p.clears[`${id}:${mode}`])return 'CLEAR済み';if(mode==='hard'&&!p.clears[`${id}:normal`])return 'LOCKED';return 'プレイ可能'}
function home(){history.pushState({},'',location.pathname);state={stage:null,mode:null,index:0,data:null,solved:false};$('#app').innerHTML=`
<section class="hero"><div class="eyebrow">A QUIET PUZZLE EXHIBITION</div><h1>神話樹の世界を、<br>静かに巡る。</h1><p class="lead">各地に残された十の謎を解き、展示室の奥へ。NORMALを終えると、同じ地域のHARDが解放されます。</p></section>
<h2 class="section-title">STAGES / 展示地域</h2><section class="stage-grid">${stages.map((s,i)=>`<article class="stage-card" style="--accent:${s.accent}"><span class="stage-index">0${i+1}</span><h2>${esc(s.name)}</h2><p>${esc(s.description)}</p><div class="modes">${['normal','hard'].map(m=>{const st=statusFor(s.id,m);return `<button class="mode-button" data-stage="${s.id}" data-mode="${m}" ${st==='LOCKED'?'disabled':''}>${m.toUpperCase()}<small>${st}</small></button>`}).join('')}</div></article>`).join('')}</section>`;
$$('.mode-button').forEach(b=>b.onclick=()=>start(b.dataset.stage,b.dataset.mode));$('#app').focus()}
const $$=(s,p=document)=>[...p.querySelectorAll(s)];
async function start(id,mode){const s=stages.find(x=>x.id===id);if(!s)return home();if(mode==='hard'&&statusFor(id,mode)==='LOCKED'){home();return}state.stage=s;state.mode=mode;state.index=0;state.solved=false;try{state.data=await fetchJSON(s[`${mode}Data`]);history.pushState({},'',`?stage=${encodeURIComponent(id)}&mode=${mode}`);renderQuestion()}catch(e){showError('問題データを読み込めませんでした。ローカルではWebサーバーから開いてください。')}}
function renderQuestion(){const q=state.data.questions[state.index],n=state.data.questions.length;state.solved=false;$('#app').innerHTML=`<section class="puzzle-shell"><div class="puzzle-meta"><span>${esc(state.stage.name)} · ${state.mode.toUpperCase()}</span><span>${state.index+1} / ${n}</span></div><div class="progress"><span style="width:${(state.index+1)/n*100}%"></span></div><div class="eyebrow">QUESTION ${String(state.index+1).padStart(2,'0')}</div><div class="question">${esc(q.question)}</div><p class="guide">${esc(state.data.inputGuide)}</p><form class="answer-area"><input id="answer" aria-label="答え" autocomplete="off" required><button class="primary" type="submit">回答する</button></form><p id="feedback" class="feedback" aria-live="polite"></p><div class="actions"><button class="secondary hint" data-hint="1">ヒント1</button><button class="secondary hint" data-hint="2">ヒント2</button><button id="next" class="primary" hidden>次へ</button><button id="backHome" class="secondary">展示室へ戻る</button></div><div id="hintBox"></div></section>`;
$('.answer-area').onsubmit=checkAnswer;$$('.hint').forEach(b=>b.onclick=()=>showHint(+b.dataset.hint));$('#next').onclick=next;$('#backHome').onclick=home;$('#answer').focus()}
async function checkAnswer(e){e.preventDefault();if(state.solved)return;const q=state.data.questions[state.index],value=$('#answer').value;const digest=await sha256(value);const fb=$('#feedback');if(digest===q.answerHash){state.solved=true;fb.className='feedback ok';fb.textContent='正解です。展示の先へ進めます。';$('#next').hidden=false;$('#answer').disabled=true}else{fb.className='feedback bad';fb.textContent='違うようです。もう一度お試しください。';$('#answer').select()}}
function showHint(n){const q=state.data.questions[state.index];$('#hintBox').innerHTML=`<div class="hint-box"><span class="eyebrow">HINT ${n}</span><br>${esc(q[`hint${n}`])}</div>`}
function next(){if(!state.solved)return;if(state.index<state.data.questions.length-1){state.index++;renderQuestion()}else complete()}
function complete(){const p=progress(),key=`${state.stage.id}:${state.mode}`;p.clears[key]=new Date().toISOString();p.achievements[key]={unlockedAt:p.clears[key],title:`${state.stage.name}（${state.mode.toUpperCase()}）をクリア`};save(p);const text=encodeURIComponent(`ZMTQ謎解き、${state.stage.name}（${state.mode.toUpperCase()}）をクリアしました。`),url=encodeURIComponent(`${location.origin}${location.pathname}?stage=${state.stage.id}&mode=${state.mode}`);$('#app').innerHTML=`<section class="clear"><div class="clear-symbol">◇</div><div class="eyebrow">EXHIBITION COMPLETED</div><h1>CLEAR</h1><p>${esc(state.stage.name)}での謎解きを終えました。</p>${state.mode==='normal'?'<p class="feedback ok">HARDが解放されました。</p>':''}<div class="clear-actions"><button id="toHome" class="primary">ステージ選択へ戻る</button><a class="secondary" target="_blank" rel="noopener" href="https://twitter.com/intent/tweet?text=${text}&url=${url}">Xで共有する</a></div></section>`;$('#toHome').onclick=home}
function showError(msg){$('#app').innerHTML=`<section class="clear"><h1>読み込みエラー</h1><p>${esc(msg)}</p><button class="primary" onclick="location.reload()">再読み込み</button></section>`}
async function modal(type){const content=$('#modalContent');if(type==='howto')content.innerHTML='<h2>遊び方</h2><p>地名ごとのステージには10問あります。ひらがなで答えを入力し、正解すると次へ進めます。NORMALをクリアすると同地域のHARDが解放されます。各問題には2つのヒントがありますが、答えそのものは表示されません。</p>';
if(type==='updates'){const u=await fetchJSON('data/updates.json');content.innerHTML=`<h2>更新情報</h2><ul class="update-list">${u.map(x=>`<li><time>${esc(x.date)}</time>${esc(x.text)}</li>`).join('')}</ul>`}
if(type==='achievements'){const a=Object.values(progress().achievements);content.innerHTML=`<h2>実績</h2>${a.length?`<ul class="achievement-list">${a.map(x=>`<li>◇ ${esc(x.title)}<br><small>${new Date(x.unlockedAt).toLocaleDateString('ja-JP')}</small></li>`).join('')}</ul>`:'<p>まだ解除された実績はありません。</p>'}`}
$('#modal').showModal()}
async function checkVersion(){try{const v=await fetchJSON(`data/version.json?t=${Date.now()}`),old=localStorage.getItem('zmtq_version');if(old&&old!==v.version)$('#updateNotice').hidden=false;localStorage.setItem('zmtq_version',v.version)}catch{}}
async function init(){try{stages=await fetchJSON('data/stages.json');$$('[data-modal]').forEach(b=>b.onclick=()=>modal(b.dataset.modal));$('.modal-close').onclick=()=>$('#modal').close();$('#reloadButton').onclick=()=>location.reload();window.onpopstate=home;const p=new URLSearchParams(location.search),id=p.get('stage'),mode=p.get('mode');if(id&&['normal','hard'].includes(mode))await start(id,mode);else home();checkVersion()}catch(e){showError('初期データを読み込めませんでした。READMEの手順で起動してください。')}}
init();
